### ISSUE TITLE
README.md: add link to referenced blog post

### ISSUE THREAD

**Issue by cxw42** [tinfoil/testable-chrome-extension-example#1]
I enjoyed [the post](https://www.tinfoilsecurity.com/blog/how-to-create-testable-modularized-chrome-browser-extensions) and I agree with the README's point that people should check out the post.  However, the README does not actually link to the post :) .  Would you please add the link?  Thanks!

**Comment by borski** [comment]
Thanks, @cxw42! Fixed.
