### ISSUE TITLE
can unittest background.js involve the chrome apis?

### ISSUE THREAD

**Issue by wuyuanyi135** [tinfoil/testable-chrome-extension-example#2]
Hello,

I found that the unittest for the background script is relatively simple. It does not invoke any chrome.* api. I wonder how can it be handled if I need to test them?

**Comment by bsedat** [comment]
Hello! Unfortunately this repo is mostly just an example and not under any active development, but I'll do my best to answer your question.
In this example we considered chrome.* API part of the integration tests and so some code samples can be found [here](https://github.com/tinfoil/testable-chrome-extension-example/blob/master/spec/integration/popup_spec.rb). 

Good luck and I'm sorry I'm not able to help out more.
